print("Please enter five numbers.")
num_1 = eval(input())
num_2 = eval(input())
num_3 = eval(input())
num_4 = eval(input())
num_5 = eval(input())
print("The average of those numbers is:")
print((num_1 + num_2 + num_3 + num_4 + num_5) / 5)
